# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52b73df580c664c3fe4a81bb2033202410f55374227c2ae3deb533c64d8f18f3f114d353b0d2e765039530343efecc3c3eb9b36a8fffae06b2030822663ce014

test:
  secret_key_base: 3025178062b96bab39a1db1d78f4da9ff8cd5a64d89a8148b40621c777bc2b5caad46848835ffe6e84e8a19d7e2f195e510c12ae51636311b7ca141af1b9c41f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
